### ISSUE TITLE
angularjs error when I enter dashboard

### ISSUE THREAD

**Issue by royzhao** [shipyard/shipyard#402]
hello! when i start shipyard,the angularjs throw an exception like that
```
 Error: [$interpolate:interr] http://errors.angularjs.org/1.2.28/$interpolate/interr?p0=%7B%7Bevent%7Cfor…%7D&p1=TypeError%3A%20Cannot%20read%20property%20'length'%20of%20undefined
    at Error (native)
    at http://172.17.0.6:8080/bower_components/angular/angular.min.js:6:450
    at Object.$get.p (http://172.17.0.6:8080/bower_components/angular/angular.min.js:80:480)
    at h.$get.h.$digest (http://172.17.0.6:8080/bower_components/angular/angular.min.js:110:238)
    at h.$get.h.$apply (http://172.17.0.6:8080/bower_components/angular/angular.min.js:113:362)
    at m (http://172.17.0.6:8080/bower_components/angular/angular.min.js:72:454)
    at w (http://172.17.0.6:8080/bower_components/angular/angular.min.js:77:463)
    at XMLHttpRequest.B.onreadystatechange (http://172.17.0.6:8080/bower_components/angular/angular.min.js:79:24)
3angular.js:10126 Error: [$interpolate:interr] http://errors.angularjs.org/1.2.28/$interpolate/interr?p0=%7B%7Bevent%7Cfor…%7D&p1=TypeError%3A%20Cannot%20read%20property%20'length'%20of%20undefined
    at Error (native)
    at http://172.17.0.6:8080/bower_components/angular/angular.min.js:6:450
    at Object.$get.p (http://172.17.0.6:8080/bower_components/angular/angular.min.js:80:480)
    at h.$get.h.$digest (http://172.17.0.6:8080/bower_components/angular/angular.min.js:110:238)
    at h.$get.h.$apply (http://172.17.0.6:8080/bower_components/angular/angular.min.js:113:362)
    at http://172.17.0.6:8080/bower_components/angular-cookies/angular-cookies.min.js:6:235
    at http://172.17.0.6:8080/bower_components/angular/angular.min.js:38:142
    at r (http://172.17.0.6:8080/bower_components/angular/angular.min.js:7:290)
    at ea (http://172.17.0.6:8080/bower_components/angular/angular.min.js:38:126)
```

finally i found the reason, the error is happen in dashborad.html
```
                    <div class="content">
                      <div class="summary">
                          {{event.time|date:'short'}} <em>{{event|formatEvent}}</em>
                      </div>
                    </div>
```
my event object content like that 
```
{
"type":"add-role",
"container":{},
"engine":{},
"time":"2015-01-26T00:50:40Z",
"message":"name=user",
"tags":["cluster","security"]
}
```
in filters.js 
```
    .filter('formatEvent', function () {
        return function (e) {
            var evt = "";
            evt += e.type + " ";
            if (e.container !== undefined) {
                evt += truncate(e.container.id) + " " + e.container.image.name + " ";
            } else if (e.engine !== undefined) {
                evt += e.engine.id + " (" + e.engine.addr + ") ";
            } else {
                if (e.message !== undefined) {
                    evt += e.message + " ";
                }
            }
            return evt;
        };
```
my event object has container obj, but this container have not property id and image, so i change code like that
```
    .filter('formatEvent', function () {
        return function (e) {
            var evt = "";
            evt += e.type + " ";
            if (e.container !== undefined && e.container.hasOwnProperty('id') && e.container.hasOwnProperty('image')) {
                evt += truncate(e.container.id) + " " + e.container.image.name + " ";
            } else if (e.engine !== undefined && e.engine.hasOwnProperty('id')&& e.engine.hasOwnProperty('addr')) {
                evt += e.engine.id + " (" + e.engine.addr + ") ";
            } else {
                if (e.message !== undefined) {
                    evt += e.message + " ";
                }
            }
            return evt;
        };
    })
```
so the problem is sloved   
is it a bug?    
sorry,my english is bad O__O"…

**Comment by isymbo** [comment]
Below diff would fix the error as well ...

<pre>
symbo@FunU:~/gitlist/afanti$ git diff controller/static/app/filters.js
diff --git a/controller/static/app/filters.js b/controller/static/app/filters.js
index 613ae1a..aa75221 100644
--- a/controller/static/app/filters.js
+++ b/controller/static/app/filters.js
@@ -54,9 +54,9 @@ angular.module('shipyard.filters', [])
         return function (e) {
             var evt = "";
             evt += e.type + " ";
-            if (e.container !== undefined) {
+            if (e.container.id !== undefined) {
                 evt += truncate(e.container.id) + " " + e.container.image.name 
-            } else if (e.engine !== undefined) {
+            } else if (e.engine.id !== undefined) {
                 evt += e.engine.id + " (" + e.engine.addr + ") ";
             } else {
                 if (e.message !== undefined) {
</pre>

**Comment by tombee** [comment]
Ah yeah, I'd seen this in issue #343.  I'll take a look.

**Comment by royzhao** [comment]
thanks for you reply
