### ISSUE TITLE
Runtime exception on non-existing containers

### ISSUE THREAD

**Issue by bcicen** [shipyard/shipyard#418]
When delete/restart/stop/start are attempted via the api, an exception results and an empty response is returned to the client.
 
```
2015/02/07 16:40:34 http: panic serving 10.255.255.26:39087: runtime error: invalid memory address or nil pointer dereference
goroutine 11192942 [running]:
net/http.func·011()
	/usr/local/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x7d9040, 0xa4e3f3)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/citadel/citadel/cluster.(*Cluster).Kill(0xc20ae26b10, 0x0, 0x9, 0x0, 0x0)
	/home/dev/dev/gocode/src/github.com/citadel/citadel/cluster/cluster.go:96 +0x9d
github.com/shipyard/shipyard/controller/manager.(*Manager).Destroy(0xc2080601b0, 0x0, 0x0, 0x0)
	/home/dev/dev/gocode/src/github.com/shipyard/shipyard/controller/manager/manager.go:443 +0x50
main.destroy(0x7f933e3027c0, 0xc20e5f85c0, 0xc21e8d0f70)
	/home/dev/dev/gocode/src/github.com/shipyard/shipyard/controller/main.go:66 +0x138
net/http.HandlerFunc.ServeHTTP(0x8ef600, 0x7f933e3027c0, 0xc20e5f85c0, 0xc21e8d0f70)
	/usr/local/go/src/pkg/net/http/server.go:1235 +0x40
...
```

**Comment by ehazlett** [comment]
Merged #419
