### ISSUE TITLE
Docker engine responds but gives no information

### ISSUE THREAD

**Issue by jankeromnes** [shipyard/shipyard#454]
I was finally able to add my local Docker daemon to Shipyard using SSL certificates.

However, even though it appears in the Engines list, and shows a response time, it looks like Shipyard can't get actual information from the Docker daemon (no version, no containers, etc). Clicking on "Dashboard" or "Containers" always redirects to "Engines", and clicking on the local engine isn't very helpful.

How can I investigate this issue?

![shipyard-problem](https://cloud.githubusercontent.com/assets/599268/6990959/5d5d084c-da7b-11e4-98d0-b5c25aebadb7.png)

**Comment by ehazlett** [comment]
Hmm I don't believe you can use 172.17.42.1 either as I dont' think it can
get to it.  Can you try the internal IP of the host itself?  Usually
something like 192.168.x.x or 10.x.x.x.?

**Comment by jankeromnes** [comment]
Thanks for the suggestion! Unfortunately, the exact same thing happens with `192.168.0.27`.

I don't think the problem is getting to the address, because when Shipyard can't talk to the IP at all, or it's not a Docker daemon (e.g. `127.0.0.1`), the engine can't be added at all. Here the engine gets added, and shows a response time, just no version or containers.

Furthermore, I was told on Docker's IRC channel that the `docker0` interface IP should be accessible from the container, so I'm assuming the problem is on Shipyard's side.

When I use the local Docker client with the certificates, both:

    $ docker --tlsverify --tlscacert=ca.crt --tlscert=shipyard.crt --tlskey=shipyard.key -H 192.168.0.27:2376

and:

    $ docker --tlsverify --tlscacert=ca.crt --tlscert=shipyard.crt --tlskey=shipyard.key -H 172.17.42.1:2376

work just fine (with different certificates though).

I'm not sure how to debug this further, maybe I can hack into Shipyard's container to see what's going wrong?

Also, thanks for all your replies up until now, I know I've been asking a lot of questions!

**Comment by ehazlett** [comment]
Ok. What do the logs from the shipyard container say?  You should be able
to get them from "docker logs shipyard".

**Comment by jankeromnes** [comment]
Ah, thanks, that command is good to know!

It says:

    INFO[0000] shipyard version 2.0.10                      
    FATA[0000] factory is not able to fill the pool: gorethink: dial tcp 172.17.0.3:28015: connection refused 
    INFO[0000] shipyard version 2.0.10                      
    INFO[0000] checking database                            
    INFO[0006] created admin user: username: admin password: shipyard 
    INFO[0006] controller listening on :8080                
    WARN[0014] unauthorized request for /api/containers from 172.17.42.1:52017 
    WARN[0014] unauthorized request for /api/events from 172.17.42.1:52017 
    WARN[0014] unauthorized request for /api/cluster/info from 172.17.42.1:52017 
    INFO[0073] loaded engine id=local-engine addr=https://192.168.0.27:2376 
    INFO[0073] added engine id=local-engine addr=https://192.168.0.27:2376 cpus=4.000000 memory=4096.000000

Then about a thousand lines of:

    WARN[6143] unable to detect docker version: Not found   
    WARN[6146] unable to detect docker version: Not found   
    WARN[6153] unable to detect docker version: Not found   
    WARN[6156] unable to detect docker version: Not found

And then:

    INFO[0000] shipyard version 2.0.10                      
    INFO[0000] checking database                            
    INFO[0000] loaded engine id=local-engine addr=https://192.168.0.27:2376 
    INFO[0000] controller listening on :8080

**Comment by rossbachp** [comment]
I got this after add my local boot2docker instance...

```
$ docker-compose logs
Attaching to shipyard_shipyard_1, shipyard_rethinkdb_1, shipyard_shipyardrethinkdbdata_1
shipyard_1              | time="2015-04-08T04:18:37Z" level="info" msg="shipyard version 2.0.10" 
shipyard_1              | time="2015-04-08T04:18:37Z" level="info" msg="checking database" 
shipyard_1              | time="2015-04-08T04:18:43Z" level="info" msg="created admin user: username: admin password: shipyard" 
shipyard_1              | time="2015-04-08T04:18:43Z" level="info" msg="controller listening on :8080" 
shipyard_1              | time="2015-04-08T04:36:36Z" level="warning" msg="unauthorized request for /api/containers from 192.168.59.3:50188" 
shipyard_1              | time="2015-04-08T04:36:36Z" level="warning" msg="unauthorized request for /api/events from 192.168.59.3:50192" 
shipyard_1              | time="2015-04-08T04:36:36Z" level="warning" msg="unauthorized request for /api/cluster/info from 192.168.59.3:50188" 
shipyard_1              | time="2015-04-08T04:37:09Z" level="warning" msg="unauthorized request for /api/containers from 192.168.59.3:50188" 
shipyard_1              | time="2015-04-08T04:37:09Z" level="warning" msg="unauthorized request for /api/events from 192.168.59.3:50193" 
shipyard_1              | time="2015-04-08T04:37:09Z" level="warning" msg="unauthorized request for /api/cluster/info from 192.168.59.3:50193" 
shipyard_1              | time="2015-04-08T04:41:19Z" level="info" msg="loaded engine id=b2d addr=https://192.168.59.103:2376" 
shipyard_1              | time="2015-04-08T04:41:19Z" level="info" msg="added engine id=b2d addr=https://192.168.59.103:2376 cpus=1.000000 memory=1024.000000" 
shipyard_1              | 2015/04/08 04:41:28 http: panic serving 192.168.59.3:50203: runtime error: index out of range
shipyard_1              | goroutine 36 [running]:
shipyard_1              | net/http.func·011()
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
shipyard_1              | runtime.panic(0x869340, 0xcf92dc)
shipyard_1              | 	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
shipyard_1              | github.com/citadel/citadel.FromDockerContainer(0xc20823df80, 0x40, 0xc2081a9690, 0xe, 0xc2080abea0, 0xc20816b7a0, 0x0, 0x0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/citadel/citadel/utils.go:91 +0xb5e
shipyard_1              | github.com/citadel/citadel.(*Engine).ListContainers(0xc2080abea0, 0xc208180001, 0x8afc60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/citadel/citadel/engine.go:183 +0x21f
shipyard_1              | github.com/citadel/citadel/cluster.(*Cluster).ListContainers(0xc20818b860, 0x8d0001, 0x8afc60, 0x0, 0x0, 0x0, 0x0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/citadel/citadel/cluster/cluster.go:84 +0x125
shipyard_1              | main.containers(0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/main.go:255 +0xa4
shipyard_1              | net/http.HandlerFunc.ServeHTTP(0x97f2a8, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
shipyard_1              | github.com/gorilla/mux.(*Router).ServeHTTP(0xc208090fa0, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
shipyard_1              | github.com/codegangsta/negroni.func·001(0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc20815f0a0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:41 +0x56
shipyard_1              | github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc20809fa60, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc20815f0a0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:24 +0x4a
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP(0x7fc51b589028, 0xc20809fa60, 0xc20808e0c0, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x56
shipyard_1              | github.com/shipyard/shipyard/controller/middleware/access.(*AccessRequired).HandlerFuncWithNext(0xc2080b3fa0, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc2081a3780)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/middleware/access/access.go:110 +0x2c1
shipyard_1              | github.com/shipyard/shipyard/controller/middleware/access.*AccessRequired.HandlerFuncWithNext·fm(0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc2081a3780)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/main.go:778 +0x4e
shipyard_1              | github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc20809fa40, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc2081a3780)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:24 +0x4a
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP(0x7fc51b589028, 0xc20809fa40, 0xc20808e0a0, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x56
shipyard_1              | github.com/shipyard/shipyard/controller/middleware/auth.(*AuthRequired).HandlerFuncWithNext(0xc2080b3f80, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc208225fa0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/middleware/auth/auth.go:85 +0x1bd
shipyard_1              | github.com/shipyard/shipyard/controller/middleware/auth.*AuthRequired.HandlerFuncWithNext·fm(0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc208225fa0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/main.go:777 +0x4e
shipyard_1              | github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc20809fa20, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520, 0xc208225fa0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:24 +0x4a
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP(0x7fc51b589028, 0xc20809fa20, 0xc20808e080, 0x7fc51b58e5a8, 0xc2081a5580, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
shipyard_1              | github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc2080bfb60, 0x7fc51b58e380, 0xc208094f00, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:73 +0x10a
shipyard_1              | net/http.(*ServeMux).ServeHTTP(0xc208023e00, 0x7fc51b58e380, 0xc208094f00, 0xc208027520)
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1511 +0x1a3
shipyard_1              | github.com/gorilla/context.func·001(0x7fc51b58e380, 0xc208094f00, 0xc208027520)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/gorilla/context/context.go:141 +0x7d
shipyard_1              | net/http.HandlerFunc.ServeHTTP(0xc2080016a0, 0x7fc51b58e380, 0xc208094f00, 0xc208027520)
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
shipyard_1              | net/http.serverHandler.ServeHTTP(0xc2080056e0, 0x7fc51b58e380, 0xc208094f00, 0xc208027520)
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1673 +0x19f
shipyard_1              | net/http.(*conn).serve(0xc208174280)
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1174 +0xa7e
shipyard_1              | created by net/http.(*Server).Serve
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1721 +0x313
```

**Comment by ehazlett** [comment]
@rossbachp hmm i believe i fixed this in master.  would you mind trying that and see if it fixes?  if so, i'll push a `2.0.11` release from current master.

**Comment by rossbachp** [comment]
OK, I check this later:)

**Comment by rossbachp** [comment]
I rebuild master
script/build 2.0.11

```
docker images |grep shipyard
shipyard/shipyard                      2.0.11              40de30eefafd        16 seconds ago      36.25 MB
shipyard-build                         latest              f6f6a21063d0        41 seconds ago      2.072 GB
```

my compose file use the build 2.0.11 images

...
   "Id": "f6491055cd3a04a23829abbfe02cd738e1ffc2a9f11aef312de9ed84683cb239",
    "Image": "40de30eefafd98033efcb0939282b0f123cd1101694b90eb6585a381ab6182c0",
    "MountLabel": "",
    "Name": "/shipyard_shipyard_1",
...

but log reports 2.0.10:

```
$ docker-compose logs
Attaching to shipyard_shipyard_1, shipyard_rethinkdb_1, shipyard_shipyardrethinkdbdata_1
shipyard_1              | time="2015-04-08T15:00:56Z" level="info" msg="shipyard version 2.0.10" 
shipyard_1              | time="2015-04-08T15:00:56Z" level="info" msg="checking database" 
shipyard_1              | time="2015-04-08T15:01:02Z" level="info" msg="created admin user: username: admin password: shipyard" 
shipyard_1              | time="2015-04-08T15:01:02Z" level="info" msg="controller listening on :8080" 
```

and failure is there:

````
shipyard_1              | 2015/04/08 14:43:43 http: panic serving 192.168.59.3:53733: runtime error: index out of range
shipyard_1              | goroutine 77 [running]:
shipyard_1              | net/http.func·011()
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1100 +0xb7
shipyard_1              | runtime.panic(0x869340, 0xcf92dc)
shipyard_1              | 	/usr/src/go/src/pkg/runtime/panic.c:248 +0x18d
shipyard_1              | github.com/citadel/citadel.FromDockerContainer(0xc2081c2c80, 0x40, 0xc20820f880, 0xe, 0xc2080c0150, 0xc20826a960, 0x0, 0x0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/citadel/citadel/utils.go:91 +0xb5e
shipyard_1              | github.com/citadel/citadel.(*Engine).ListContainers(0xc2080c0150, 0xc2080f0001, 0x8afc60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/citadel/citadel/engine.go:183 +0x21f
shipyard_1              | github.com/citadel/citadel/cluster.(*Cluster).ListContainers(0xc2080f0090, 0x8d0001, 0x8afc60, 0x0, 0x0, 0x0, 0x0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/citadel/citadel/cluster/cluster.go:84 +0x125
shipyard_1              | main.containers(0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/main.go:255 +0xa4
shipyard_1              | net/http.HandlerFunc.ServeHTTP(0x97f2a8, 0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0)
shipyard_1              | 	/usr/src/go/src/pkg/net/http/server.go:1235 +0x40
shipyard_1              | github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080916d0, 0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x292
shipyard_1              | github.com/codegangsta/negroni.func·001(0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0, 0xc2080438c0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:41 +0x56
shipyard_1              | github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc2080014f0, 0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0, 0xc2080438c0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:24 +0x4a
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP(0x7f13da732298, 0xc2080014f0, 0xc20806c6c0, 0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x8c
shipyard_1              | github.com/codegangsta/negroni.middleware.ServeHTTP·fm(0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/Godeps/_workspace/src/github.com/codegangsta/negroni/negroni.go:33 +0x56
shipyard_1              | github.com/shipyard/shipyard/controller/middleware/access.(*AccessRequired).HandlerFuncWithNext(0xc20806c520, 0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0, 0xc2080ab260)
shipyard_1              | 	/go/src/github.com/shipyard/shipyard/controller/middleware/access/access.go:110 +0x2c1
shipyard_1              | github.com/shipyard/shipyard/controller/middleware/access.*AccessRequired.HandlerFuncWithNext·fm(0x7f13da732db8, 0xc2081989c0, 0xc2081b1ba0, 0xc2080ab260)
s
```

Is my shipyard controller build broken?

**Comment by jankeromnes** [comment]
It looks like my original issue has been fixed. Thanks! (I'll reopen this if I encounter the issue again.)

@rossbachp I believe your problem is slightly different, so maybe it makes sense to open a separate GitHub issue if you still need help.
