### ISSUE TITLE
coreOS // shipyard cli not working

### ISSUE THREAD

**Issue by helix01** [shipyard/shipyard#620]
I used *curl -sSL https://shipyard-project.com/deploy | bash -s* to deploy shipyard on my fresh coreOS install (Linux core 4.1.6-coreos-r1). The webinterface seems to working fine, but i cant use any commands via the cli.
```
core ~ # docker run -it --rm shipyard/shipyard-cli
Unable to find image 'shipyard/shipyard-cli:latest' locally
Pulling repository shipyard/shipyard-cli
b73f9452c2ff: Download complete
511136ea3c5a: Download complete
16386e29a1f4: Download complete
835c4d274060: Download complete
822b564bccc7: Download complete
d021daf25fb3: Download complete
c2dfcd48a7c7: Download complete
6c27e998c8b0: Download complete
6f66a854f309: Download complete
d743234d68d6: Download complete
Status: Downloaded newer image for shipyard/shipyard-cli:latest
shipyard cli> shipyard login
URL: http://<publicIP>:8080
Username: admin
Password:
shipyard cli> shipyard containers
FATA[0000] error getting containers: 404 page not found

shipyard cli> shipyard accounts
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x401195]

goroutine 16 [running]:
runtime.panic(0x713aa0, 0x91e193)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.accountsAction(0xc208042210)
        /home/dev/dev/gocode/src/github.com/shipyard/shipyard/cli/accounts.go:35 +0x595
github.com/codegangsta/cli.Command.Run(0x76c0f0, 0x8, 0x0, 0x0, 0x774c10, 0xd, 0x0, 0x0, 0x0, 0x0, ...)
        /home/dev/dev/gocode/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/codegangsta/cli.(*App).Run(0xc2080540c0, 0xc20800e000, 0x2, 0x2, 0x0, 0x0)
        /home/dev/dev/gocode/src/github.com/codegangsta/cli/app.go:125 +0x941
main.main()
        /home/dev/dev/gocode/src/github.com/shipyard/shipyard/cli/cli.go:65 +0x4f9

goroutine 19 [finalizer wait]:
runtime.park(0x4244c0, 0x922cb8, 0x920f09)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x922cb8, 0x920f09)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 22 [runnable]:
net/http.(*persistConn).readLoop(0xc2080422c0)
        /usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc2080422c0)
        /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
```
```
core ~ # docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                            NAMES
53e332cb7b20        shipyard/shipyard-cli          "/bin/bash"            10 minutes ago      Up 10 minutes                                        silly_lalande        
ee58b4f79758        shipyard/shipyard:latest       "/bin/controller ser   13 minutes ago      Up 13 minutes       0.0.0.0:8080->8080/tcp           shipyard-controller  
fb2c20b4bd53        swarm:latest                   "/swarm m --host tcp   13 minutes ago      Up 13 minutes       2375/tcp                         shipyard-swarm       
cacbc22954db        ehazlett/docker-proxy:latest   "/usr/local/bin/run"   13 minutes ago      Up 13 minutes       2375/tcp                         shipyard-proxy       
4ac32e5a34c3        alpine                         "sh"                   14 minutes ago      Up 14 minutes                                        shipyard-certs       
a0bf711ef35e        rethinkdb                      "rethinkdb --bind al   14 minutes ago      Up 14 minutes       8080/tcp, 28015/tcp, 29015/tcp   shipyard-rethinkdb
```

```
docker -v
Docker version 1.7.1, build 2c2c52b-dirty
```

If you need further infos let me know.

**Comment by tombee** [comment]
Hi @helix01, you no longer need to use the shipyard-cli.

You should be able to use the standard docker binary directly against the shipyard controller instead and run a `docker ps -a` to list containers.

**Comment by helix01** [comment]
Hey @tombee, thanks for the fast response. I'm quite new to these concepts of docker etc. So, i stumbled across this because i saw a video about how to integrate interlock with shipyard (https://asciinema.org/a/13318) also *Auto Deploy via Docker Hub* (https://asciinema.org/a/12434). How do i interact with the controller now? Sadly, i cant find any docs about it.

**Comment by ehazlett** [comment]
That is deprecated.  That was for Shipyard 2.x.  In v3, it's pretty simple
to do the same thing you just need to point interlock at Swarm.

For the Deploy Hooks in v3, see
http://shipyard-project.com/docs/api/#webhook-keys

**Comment by helix01** [comment]
I'll give it a try, thanks a lot!
