### ISSUE TITLE
Problem with deploy webhookkey

### ISSUE THREAD

**Issue by decker502** [shipyard/shipyard#718]
hi,

Controller threw nil pointer exception when deploy webhookkey

controller's output is:

```
INFO[439460] created service key key=bqPTOad0aPZ7NptKqK9pabJu53rF8JdH6rFO description=xxx 
INFO[439460] saved webhook key image=library/nginx:1.9.9  
2016/01/02 12:40:07 http: panic serving 192.168.0.1:40221: runtime error: invalid memory address or nil pointer dereference
goroutine 995 [running]:
net/http.(*conn).serve.func1(0xc8206b0160, 0x7f43f050de48, 0xc8201c20c0)
        /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/shipyard/shipyard/controller/api.(*Api).hubWebhook(0xc82007d040, 0x7f43f05179a0, 0xc82017c790, 0xc8203ab500)
        /home/ehazlett/dev/gocode/src/github.com/shipyard/shipyard/controller/api/webhook.go:28 +0x91e
github.com/shipyard/shipyard/controller/api.(*Api).(github.com/shipyard/shipyard/controller/api.hubWebhook)-fm(0x7f43f05179a0, 0xc82017c790, 0xc8203ab500)
        /home/ehazlett/dev/gocode/src/github.com/shipyard/shipyard/controller/api/api.go:185 +0x3e
```

**Comment by ehazlett** [comment]
What was the payload sent?  Was this from the docker hub?

**Comment by decker502** [comment]
Payload is ```library/nginx:1.9.9```

The request is sent manually

**Comment by ehazlett** [comment]
This is most likely a malformed request.  Check http://shipyard-project.com/docs/api/#create-a-webhook-key to make sure you specify the correct format.  Please open a new issue if you continue to have issues.  Thanks!
