### ISSUE TITLE
Showing logs of Container leads to a "Bad Parse" exception sometimes

### ISSUE THREAD

**Issue by jhiemer** [shipyard/shipyard#774]
Hi,
the following error occurs sometimes, when trying to retrieve the logs via shipyard ui:

````bash
Error: [$sanitize:badparse] http://errors.angularjs.org/1.3.20/$sanitize/badparse?p0=%3Cpackages%40erlang-solutions.com%3E%22%20imported%0D%0A2016-03-06T18%3A19%3A50.603351365Z%20gpg%3A%20Total%20number%20processed%3A%201%0D%0A2016-03-06T18%3A19%3A50.603660976Z%20gpg%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20imported%3A%201%20%20(RSA%3A%201)%0D%0A2016-03-
....
...%20completed%20with%206%20plugins.%0D%0A
    at Error (native)
    at http://host:8080/bower_components/angular/angular.min.js:6:417
    at F (http://host:8080/bower_components/angular-sanitize/angular-sanitize.min.js:8:428)
    at http://host:8080/bower_components/angular-sanitize/angular-sanitize.min.js:14:183
    at getTrusted (http://host:8080/bower_components/angular/angular.min.js:133:271)
    at Object.d.(anonymous function) [as getTrustedHtml] (http://host:8080/bower_components/angular/angular.min.js:134:478)
    at Object.fn (http://host:8080/bower_components/angular/angular.min.js:215:395)
    at n.$digest (http://host:8080/bower_components/angular/angular.min.js:124:114)
    at n.$
`````

**Comment by tombee** [comment]
I think this is fixed in master (#PR 749).

**Comment by jhiemer** [comment]
Yes, perfect. Thanks!
